#!/usr/bin/env php
<?php
date_default_timezone_set("Europe/Moscow");
if (!@include_once __DIR__ . '/vendor/autoload.php') {
    echo "ERROR - can't find vendor/autoload.php file. Please ensure packages are installed via 'composer install'", PHP_EOL;
    exit(1);
}

define('ROOT_PATH', __DIR__ );
define('MIGRATIONS_PATH', __DIR__ . '/app/database/migrations');
define('SEEDS_PATH', __DIR__ . '/app/database/seeds');
define('COMMANDS_PATH', __DIR__ . '/app/src/Commands');
define('CONFIG_PATH', __DIR__ . '/config');
define('APP_PATH', __DIR__ . '/app');

define('MIGRATIONS_TABLE', 'migrations');
define('SEEDS_TABLE', 'seeds');

use Illuminate\Database\Capsule\Manager as Capsule;
use Illuminate\Events\Dispatcher;
use Illuminate\Container\Container;
use App\Commands;
use App\Common\Helper;

class Partisan
{
    private $args;

    private $commands;

    private $config  = null;

    private $capsule = null;

    function __construct($args)
    {
        $this->args = $args;

        $files = glob(COMMANDS_PATH.'/*.php');
        $this->commands = $this->getCommandList($files);
    }

    public function exec()
    {
        if (count($this->args) <= 1) {
            $this->help();

            return;
        }

        switch ($this->args[1]) {
            case "generate":
                if (count($this->args) < 4){
                    echo "Missing required attributes".PHP_EOL;
                    return;
                }
                if ($this->args[2] == 'seed'){
                    $path = SEEDS_PATH;
                } else {
                    $path = MIGRATIONS_PATH;
                }
                $this->runGenerate($path, $this->args[3]);
                break;

            case "migrate":
                $this->runMigrations();
                if (isset($this->args[2]) && $this->args[2] == '--seed') {
                    $this->runSeed();
                }
                break;

            case "seed":
                $this->runSeed();
                break;

            case "docsgenerate":
                echo exec('apidoc -i ./app -o ./docs -t ./docstemplate').PHP_EOL;
                break;

            case "runTest":
                echo exec('./vendor/bin/codecept run').PHP_EOL;
                break;

            case "help":
            case "--help":
                $this->help();
                break;

            default:
                if (in_array($this->args[1], $this->commands)) {
                    $this->runCommand();
                } else {
                      echo "Command not found".PHP_EOL;
                }
                break;
        }
    }

    private function help()
    {
        echo "\n";
        echo "syntaxis: php partisan <command> [<args>]".PHP_EOL;
        echo PHP_EOL;
        echo "Commands: \n";
        echo "php partisan --help                               -->   Displays the help menu.".PHP_EOL;
        echo "php partisan generate migration <migrationName>   -->   Generate a new migration.".PHP_EOL;
        echo "php partisan generate seed <seedName>             -->   Generate a new seed.".PHP_EOL;
        echo "php partisan migrate                              -->   Migrate the database.".PHP_EOL;
        echo "php partisan seed                                 -->   Seed the database tables.".PHP_EOL;
        echo "php partisan migrate --seed                       -->   Migrate and seed the database.".PHP_EOL;
        //echo "php partisan down <migrationId>                   -->   Revert a specific migration.".PHP_EOL;
        echo "php partisan <commandsName> <action> [<args>]     -->   Running a specific console commands.".PHP_EOL;
        echo "php partisan docsgenerate                         -->   Generate documentation.".PHP_EOL;
        echo "php partisan runTest <args>                       -->   Run test suite.".PHP_EOL;
        echo PHP_EOL;
    }

    private function runMigrations()
    {
        $this->dbConnect();
        $this->safeCreateTable(MIGRATIONS_TABLE);

        $files = glob(MIGRATIONS_PATH.'/*.php');
        $this->run($files);
    }

    private function runSeed()
    {
        $this->dbConnect();
        $this->safeCreateTable(SEEDS_TABLE);

        $files = glob(SEEDS_PATH.'/*.php');
        $this->run($files, 'seed');
    }

    private function runGenerate($path, $migrationName)
    {
        $templatePath = $path . '/.template.php';

        if (!is_writeable($path)) {
            echo 'The directory ' . $path . ' is not writeable'.PHP_EOL;
            return;
        }

        if (false === file_exists($templatePath)) {
            echo 'The template file ' . $templatePath . ' not found'.PHP_EOL;
            return;
        };

        $baseName  = date('YmdHis') . '_' . $migrationName . '.php';
        $className = $migrationName; // need for template

        if (file_exists($baseName)) {
            echo 'The file ' . $templatePath . ' already exists'.PHP_EOL;
            return;
        };

        ob_start();
        include($templatePath);
        $contents = ob_get_clean();

        if (false === file_put_contents($path . '/' . $baseName, $contents)) {
            echo 'The file ' . $templatePath . ' could not be written to'.PHP_EOL;
            return;
        };

        echo "Generate completed".PHP_EOL;
    }

    private function runCommand()
    {
        if (!isset($this->args[2])) {
            $action = 'index'; // default action
        } else {
            $action = $this->args[2];
        }

        $class  = 'App\Commands\\'.ucfirst($this->args[1]).'Controller';
        $action = 'action'.ucfirst($action);

        if (is_callable([$class, $action])) {
            $obj = new $class($this->args);

            call_user_func([$obj, $action]);
        } else {
            echo "action not found".PHP_EOL;
        }
    }

    private function run($files, $type = 'migration')
    {
        foreach ($files as $file) {
            require_once($file);

            $fileName = explode('_', basename($file, '.php'));
            $class    = '';

            foreach($fileName as $key => $item){
                if ($key == 0) continue;
                $class .= ucfirst($item);
            }

            echo basename($file, '.php');

            $table = ($type == 'migration') ? MIGRATIONS_TABLE : SEEDS_TABLE;

            if ($this->isExistRow(basename($file, '.php'), $table)) {
                echo ' - already exists.'.PHP_EOL;
            } else {
                $obj = new $class();
                if($type == 'migration'){
                    $obj->up();
                } else {
                    $obj->run();
                }
                $this->insertRow(basename($file, '.php'), $table);
                echo ' - done.'.PHP_EOL;
            }
        }
        echo ucfirst($type) . ' completed.'.PHP_EOL;
    }

    private function getCommandList($files)
    {
        $commands = [];

        foreach ($files as $file) {
            $commands[] = $this->getCommandName($file);
        }

        return $commands;
    }

    private function getCommandName($file)
    {
        return str_replace('controller', '', strtolower(basename($file, '.php')));
    }

    private function dbConnect()
    {
        if (empty($this->config)) {
            $this->config  = require_once APP_PATH . '/settings.php';
        }

        if (empty($this->capsule)) {
            $this->capsule = new Capsule;

            $this->capsule->addConnection($this->config['settings']['database']['connections']['default'], 'default');
            $this->capsule->setEventDispatcher(new Dispatcher(new Container));
            $this->capsule->setAsGlobal();
            $this->capsule->bootEloquent();
        }
    }

    private function safeCreateTable($tableName)
    {
        if (!Capsule::schema()->hasTable($tableName)) {
            Capsule::schema()->create($tableName, function($table)
            {
                $table->string('version');
                $table->timestamp('apply_time')->useCurrent();

                $table->primary('version');
            });
        }
    }

    private function isExistRow($name, $table)
    {
        $item = Capsule::table($table)->where('version', $name)->first();
        return !is_null($item);
    }

    private function insertRow($name, $table)
    {
        Capsule::table($table)->insert([
            'version' => $name,
        ]);
    }

}

$partisan = new Partisan($argv);
$partisan->exec();
