#!/usr/bin/env php
<?php
date_default_timezone_set("Europe/Moscow");
if (!@include_once __DIR__ . '/vendor/autoload.php') {
    echo "ERROR - can't find vendor/autoload.php file. Please ensure packages are installed via 'composer install'", PHP_EOL;
    exit(1);
}

define('ROOT_PATH', __DIR__ );
define('MIGRATIONS_PATH', __DIR__ . '/app/database/migrations');
define('SEEDS_PATH', __DIR__ . '/app/database/seeds');
define('COMMANDS_PATH', __DIR__ . '/app/src/Commands');
define('CONFIG_PATH', __DIR__ . '/config');
define('APP_PATH', __DIR__ . '/app');

define('MIGRATIONS_TABLE', 'migrations');
define('SEEDS_TABLE', 'seeds');

use Illuminate\Database\Capsule\Manager as Capsule;
use Illuminate\Events\Dispatcher;
use Illuminate\Container\Container;
use App\Commands;
use App\Common\Helper;

class Partisan
{
    private $args;

    private $commands;

    private $config  = null;

    private $capsule = null;

    /**
     * @var int exit code - all went well
     */
    const EXIT_CODE_OK = 0;

    /**
     * @var int exit code - incorrect CLI arguments list
     */
    const EXIT_CODE_ARGS_LIST = 10;

    /**
     * @var int exit code - some kind of file/DB access error
     */
    const EXIT_CODE_ACCESS_ERROR = 11;

    /**
     * Partisan constructor.
     * @param $args
     */
    function __construct($args)
    {
        $this->args = $args;

        $files = glob(COMMANDS_PATH.'/*.php');
        $this->commands = $this->getCommandList($files);
    }

    /**
     * @return int|mixed|null|void
     */
    public function exec()
    {
        if (count($this->args) <= 1) {
            $this->help();

            return static::EXIT_CODE_ARGS_LIST;
        }

        switch ($this->args[1]) {
            case "generate":
                if (count($this->args) < 4){
                    echo "Missing required attributes".PHP_EOL;
                    return static::EXIT_CODE_ARGS_LIST;
                }

                if ($this->args[2] == 'seed'){
                    $path = SEEDS_PATH;
                } else {
                    $path = MIGRATIONS_PATH;
                }

                return $this->runGenerate($path, $this->args[3]);

            case "migrate":
                $ret = $this->runMigrations();

                // run seeding only in case migrations are OK
                if ($ret === static::EXIT_CODE_OK && isset($this->args[2]) && $this->args[2] == '--seed') {
                    $ret = $this->runSeed();
                }
                return $ret;

            case "seed":
                return $this->runSeed();

            case "docsgenerate":
                echo exec('apidoc -i ./app -o ./docs -t ./docstemplate').PHP_EOL;
                return static::EXIT_CODE_OK;

            case "runTest":
                echo exec('./vendor/bin/codecept run').PHP_EOL;
                return static::EXIT_CODE_OK;

            case "help":
            case "--help":
                $this->help();
                return static::EXIT_CODE_OK;

            default:
                if (in_array($this->args[1], $this->commands)) {
                    return $this->runCommand();
                } else {
                    echo "Command not found".PHP_EOL;
                    return static::EXIT_CODE_ARGS_LIST;
                }
        }
    }

    /**
     *
     */
    private function help()
    {
        echo PHP_EOL;
        echo "syntaxis: php partisan <command> [<args>]", PHP_EOL;
        echo PHP_EOL;
        echo "Commands: ", PHP_EOL;
        echo "php partisan --help                               -->   Displays the help menu.",              PHP_EOL;
        echo "php partisan generate migration <migrationName>   -->   Generate a new migration.",            PHP_EOL;
        echo "php partisan generate seed <seedName>             -->   Generate a new seed.",                 PHP_EOL;
        echo "php partisan migrate                              -->   Migrate the database.",                PHP_EOL;
        echo "php partisan seed                                 -->   Seed the database tables.",            PHP_EOL;
        echo "php partisan migrate --seed                       -->   Migrate and seed the database.",       PHP_EOL;
        //echo "php partisan down <migrationId>                   -->   Revert a specific migration.", PHP_EOL;
        echo "php partisan <commandsName> <action> [<args>]     -->   Running a specific console commands.", PHP_EOL;
        echo "php partisan docsgenerate                         -->   Generate documentation.",              PHP_EOL;
        echo "php partisan runTest <args>                       -->   Run test suite.",                      PHP_EOL;
        echo PHP_EOL;
    }

    /**
     *
     */
    private function runMigrations()
    {
        $this->dbConnect();
        $this->safeCreateTable(MIGRATIONS_TABLE);

        $files = glob(MIGRATIONS_PATH.'/*.php');
        return $this->run($files);
    }

    /**
     *
     */
    private function runSeed()
    {
        $this->dbConnect();
        $this->safeCreateTable(SEEDS_TABLE);

        $files = glob(SEEDS_PATH.'/*.php');
        return $this->run($files, 'seed');
    }

    /**
     * @param $path
     * @param $migrationName
     * @return int
     */
    private function runGenerate($path, $migrationName)
    {
        $templatePath = $path . '/.template.php';

        if (!is_writeable($path)) {
            echo 'The directory ' . $path . ' is not writeable'.PHP_EOL;
            return static::EXIT_CODE_ACCESS_ERROR;
        }

        if (false === file_exists($templatePath)) {
            echo 'The template file ' . $templatePath . ' not found'.PHP_EOL;
            return static::EXIT_CODE_ACCESS_ERROR;
        };

        $baseName  = date('YmdHis') . '_' . $migrationName . '.php';
        $className = $migrationName; // need for template

        if (file_exists($baseName)) {
            echo 'The file ' . $templatePath . ' already exists'.PHP_EOL;
            return static::EXIT_CODE_ACCESS_ERROR;
        };

        ob_start();
        include($templatePath);
        $contents = ob_get_clean();

        if (false === file_put_contents($path . '/' . $baseName, $contents)) {
            echo 'The file ' . $templatePath . ' could not be written to'.PHP_EOL;
            return static::EXIT_CODE_ACCESS_ERROR;
        };

        echo "Generate completed".PHP_EOL;

        return static::EXIT_CODE_OK;
    }

    /**
     * @return mixed|null
     */
    private function runCommand()
    {
        if (!isset($this->args[2])) {
            $action = 'index'; // default action
        } else {
            $action = $this->args[2];
        }

        $class  = 'App\Commands\\'.ucfirst($this->args[1]).'Controller';
        $action = 'action'.ucfirst($action);

        if (is_callable([$class, $action])) {
            $obj = new $class($this->args);

            return call_user_func([$obj, $action]);
        } else {
            echo "action not found".PHP_EOL;
            return NULL;
        }
    }

    /**
     * @param $files
     * @param string $type
     */
    private function run($files, $type = 'migration')
    {
        foreach ($files as $file) {
            // file = path/to/20160706231338_create_users_table.php

            if (!is_readable($file)) {
                // file is not read-accessible
                continue;
            }

            require_once($file);

            // migration_token = 20160706231338_create_users_table
            $migration_token = basename($file, '.php');

            // filename_parts = 20160706231338_create_users_table
            $filename_parts  = explode('_', $migration_token);

            // name of the class to instantiate
            $class = '';

            foreach($filename_parts as $key => $filename_part){
                if ($key == 0) {
                    // skip date time section in file name
                    continue;
                }

                // build class name as CreateUsersTable
                $class .= ucfirst($filename_part);
            }

            echo $migration_token;

            $table = ($type == 'migration') ? MIGRATIONS_TABLE : SEEDS_TABLE;

            if ($this->isRowExist($migration_token, $table)) {
                echo ' - already exists.', PHP_EOL;
            } else {
                $obj = new $class();
                if($type == 'migration'){
                    $obj->up();
                } else {
                    $obj->run();
                }
                $this->insertRow($migration_token, $table);
                echo ' - done.', PHP_EOL;
            }
        }

        echo ucfirst($type), ' completed.', PHP_EOL;
    }

    /**
     * @param $files
     * @return array
     */
    private function getCommandList($files)
    {
        $commands = [];

        foreach ($files as $file) {
            $commands[] = $this->getCommandName($file);
        }

        return $commands;
    }

    /**
     * @param $file
     * @return mixed
     */
    private function getCommandName($file)
    {
        return str_replace('controller', '', strtolower(basename($file, '.php')));
    }

    /**
     *
     */
    private function dbConnect()
    {
        if (empty($this->config)) {
            echo "Include config ", PHP_EOL;
            $this->config  = require_once APP_PATH . '/settings.php';
        }

        if (empty($this->capsule)) {
            echo "Instantiate Capsule() ", PHP_EOL;

            $this->capsule = new Capsule();

            try {
                $this->capsule->addConnection($this->config['settings']['database']['connections']['default'], 'default');
                $this->capsule->setEventDispatcher(new Dispatcher(new Container));
                $this->capsule->setAsGlobal();
                $this->capsule->bootEloquent();
            } catch (Exception $ex) {
                echo "ERROR - can't init Capsule() - ", $ex->getMessage(), PHP_EOL;
            }
        }
    }

    /**
     * @param $tableName
     */
    private function safeCreateTable($tableName)
    {
        echo "Ensure table '$tableName' presence ", PHP_EOL;

        try {
            if (!Capsule::schema()->hasTable($tableName)) {
                Capsule::schema()->create($tableName, function($table)
                {
                    $table->string('version');
                    $table->timestamp('apply_time')->useCurrent();

                    $table->primary('version');
                });
            }
        } catch (Exception $ex) {
            echo "ERROR - can't ensure table '$tableName' presence. Please verify DB connection params and presence of database named '{$this->config['settings']['database']['connections']['default']['database']}'", PHP_EOL;
            echo "Error description: ", $ex->getMessage(), PHP_EOL;
            echo PHP_EOL;
        }
    }

    /**
     * @param $name
     * @param $table
     * @return bool
     */
    private function isRowExist($name, $table)
    {
        $item = Capsule::table($table)->where('version', $name)->first();
        return !is_null($item);
    }

    /**
     * @param $name
     * @param $table
     */
    private function insertRow($name, $table)
    {
        Capsule::table($table)->insert([
            'version' => $name,
        ]);
    }

}

$partisan = new Partisan($argv);
exit ($partisan->exec());
