<?php

return [
    'name'        => 'Bootstrapi',
    'version'     => '1.0.0',
    'description' => 'Bootstrapi docs',
    'title'       => 'Bootstrapi docs',
    'template'    => [
        'withCompare'   => false,
        'withGenerator' => false,
    ],
    'header'      => [
        'title'    => 'Начало',
        'filename' => 'header.md',
    ],
    'order'       => [
        'Token',
        'CreateToken',
        'RefreshToken',
        'User',
        'GetUsers',
        'GetUser',
        'CreateUser',
        'UpdateUser',
        'DeleteUser',
        'RequestPasswordReset',
        'PasswordReset',
        'Role',
        'GetRoles',
        'GetRole',
        'CreateRole',
        'UpdateRole',
        'DeleteRole',
        'Right',
        'GetRights',
        'GetRight',
        'CreateRight',
        'UpdateRight',
        'DeleteRight',
        'Log',
        'GetLogs',
        'GetLog',
    ],
];
